= Custom HTTP Headers

* Proposal: link:./SPICE-0022-http-headers.adoc[SPICE-0022]
* Author: link:https://github.com/kyokuping[kyokuping]
* Status: Accepted
* Implemented in: 0.32
* Category: Language, Standard Library, Tooling

== Introduction

This SPICE proposes a new evaluator option to allow adding custom HTTP headers to outbound requests, with the ability to target specific URL prefixes.

== Motivation

When Pkl interacts with HTTP resources, it may need to provide authentication tokens or other custom headers to access them. For example, a Pkl module might be hosted in a private repository that requires an `Authorization` header for access.

Currently, there is no way to add custom headers to Pkl's HTTP requests. This limits Pkl's ability to interact with a wide range of HTTP-based resources.

== Proposed Solution

A new HTTP setting will be added, called `headers`. This setting allows users to specify a list of headers to be added to outbound HTTP requests. To avoid leaking credentials, headers can be configured on a per-URL-pattern basis.

For example, to provide an authentication token for specific subdomains, the configuration would look like this:

.~/.pkl/settings.pkl
[source,pkl]
----
amends "pkl:settings"

http {
  headers {
    ["https://*.my.private.repo/*"] {
      ["authorization"] = "Bearer my-secret-token"
    }
  }
}
----

This will add the `authorization` header to all requests sent to `https://*.my.private.repo/` (subdomains of `my.private.repo`) and its subpaths.

== Detailed design

The `pkl.EvaluatorSettings.Http` class will be extended with a new `headers` property.

.pkl:EvaluatorSettings
[source,pkl]
----
class Http {
  // ... existing properties

  /// HTTP headers to add to outbound requests targeting specified URLs.
  headers: Mapping<String(isGlobPattern), HttpHeaders>?
}
----

The details for `HttpHeaders` will be provided in the following sections.

A new CLI flag, `--http-header`, will be introduced to allow specifying headers from the command line. The flag will accept key-value pairs in the format `<url-pattern>=<header-name>:<header-value>[,<header-name>:<header-value>...]`.

Example:
[source,shell]
----
pkl eval \
  --http-header "https://*.my.private.repo/*:authorization=Bearer my-secret-token" \
  myModule.pkl
----

The HTTP client will be modified to check for matching header configurations for each outgoing request and add the corresponding headers.

=== The `HttpHeaders` typealias

The `HttpHeaders` typealias is used to represent a mapping of <<header-name,header names>> to header value(s).

[source,pkl]
----
/// A mapping of header names to header value(s).
///
/// The mapping must have distinct header keys (case insensitive).
@Since { version = "0.32.0" }
typealias HttpHeaders =
  Mapping<HttpHeaderName, *Listing<HttpHeaderValue> | HttpHeaderValue>(
    keys.toList().isDistinctBy((it) -> it.toLowerCase()),
  )

/// An HTTP header value.
///
/// It consists of ASCII characters between the range of 0x20 - 0x7E, and 0x80 - 0xFF (all visible
/// ASCII characters), and also the tab character.
@Since { version = "0.32.0" }
typealias HttpHeaderValue =
  String(matches(Regex(#"[\t\u0020-\u007E\u0080-\u00FF]*"#)), length < 4096)

----

[[header-name]]
=== The `HttpHeaderName` typealias

The `HttpHeaderName` typealias is used to represent the name of an HTTP header, defined as follows:

.pkl:EvaluatorSettings
[source,pkl]
----
// Reserved HTTP header names that are inappropriate to be set by the user
typealias ReservedHttpHeaderName =
  "connection"
    | "content-length"
    | "expect"
    | "host"
    | "keep-alive"
    | "te"
    | "trailer"
    | "transfer-encoding"
    | "upgrade"

local const reservedHttpHeaderPrefix =
  Set(
    "proxy-",
    "sec-",
  )

local const isNotReservedHeaderName = (header: String) ->
  !(header.toLowerCase() is ReservedHttpHeaderName)

local const doesNotStartWithReservedPrefix = (header: String) ->
  !reservedHttpHeaderPrefix.any((it) -> header.toLowerCase().startsWith(it))

local const hasValidHeaderNameSyntax = (header: String) ->
  header.matches(Regex(#"[a-zA-Z0-9!#$%&'*+-.^_`|~]+"#))

/// An HTTP header name.
///
/// It conforms to the following rules:
///
/// * It is not one of "connection", "keep-alive", "content-length", "expect", "host", "upgrade",
///   "te", "transfer-encoding", "trailer" (case insensitive).
/// * It does not start with "proxy-" nor "sec-".
/// * It consists of a-z, A-Z, or a character in "!#$%&'*+-.^_`|~".
/// * It is not a blank string.
@Since { version = "0.32.0" }
typealias HttpHeaderName =
  String(
    isNotReservedHeaderName,
    doesNotStartWithReservedPrefix,
    hasValidHeaderNameSyntax,
    isNotBlank,
  )
----

== Compatibility

This change is strictly backward-compatible. Existing Pkl programs will continue to work as-is.

== Future directions

Future enhancements could include support for more complex header manipulation, such as removing default headers.

== Alternatives considered

=== Global HTTP headers

The initial proposal involved a simpler approach of having a single set of custom headers that would be applied to all outbound HTTP requests. This was rejected due to security concerns. Sending the same set of headers, which might include authentication tokens, to all hosts is a significant security risk. The per-URL-prefix approach provides a more secure way to manage custom headers.

=== Auth-specific support

Someone could argue it'd make more sense to specifically support auth handling rather than exposing the full ability to add custom HTTP headers. While this can be considered more future-proof in terms of exposing minimal API surface to maintain compatibility, this would limit the potential of supporting many different use cases outside of auth. That being said, adding separate auth support can also be considered later, mostly for supporting complex auth flows like OAuth.

=== Plain Text Patterns

The initial proposal used plain text prefixes for matching URLs. After considering use cases that require more flexible matching, the design was updated to use glob patterns.

Glob patterns allow for more powerful and concise rules. For example, a single pattern like `*.service.internal` can apply a common authentication header to all internal services. Similarly, a pattern like `*.my-company.com` can apply a rule to all subdomains of a company.

== Acknowledgements

Thanks to the Pkl team for their feedback on the initial proposal, which helped shape the more secure and flexible design presented in this SPICE.
