= C library for Pkl

* Proposal: link:./SPICE-0015-c-library-for-pkl.adoc[SPICE-0015]
* Author: https://github.com/kushalp[Kushal Pisavadia]
* Status: Accepted
* Implemented in: Pkl 0.33
* Category: Tooling

== Introduction

This SPICE proposes a native C library for Pkl that can be used to implement native bindings from other languages such as Swift, Go, or Python.

This would allow bindings such as `pkl-swift` and `pkl-go` to bind to Pkl without needing to spawn a child process.

== Motivation

By offering C bindings, Pkl can increase its utility and applicability across more domains, attracting a broader developer base.
These bindings would also allow language integrations to have a much smaller footprint than existing approaches requiring an external process.

== Proposed Solution

A static library and a shared library will be produced for each OS/architecture that Pkl supports, allowing users to initialise a Pkl evaluator, send messages to it, and receive messages from it.

== Detailed design

We would utilise the https://www.graalvm.org/latest/reference-manual/native-image/guides/build-native-shared-library/[native shared library functionality] of `native-image` to build upon the existing code that we already have.

However, as we’re exposing a C API to our users, we shouldn’t expose GraalVM behaviours for future-compatibility.

Pkl already has a https://pkl-lang.org/main/current/bindings-specification/message-passing-api.html[Message Passing API] with MsgPack that we can utilise here.

.pkl.h
[source,c]
----
#if defined(_WIN32)
#define PKL_EXPORT __declspec(dllexport)
#else
#define PKL_EXPORT __attribute__((visibility("default")))
#endif

#define PKL_ERR_THREAD    1     /* Called using the same pexec_t but from a different thread */
#define PKL_ERR_PROTOCOL  2     /* Failed to decode a message */

/** Error details that occurred during a method call */
typedef struct {
	char *message;
} pkl_error_t;

/**
 * Pkl executor instance that manages communication with the Pkl runtime.
 *
 * Instances should be created via `pkl_init` and destroyed via `pkl_close`.
 *
 * All calls using this executor should be synchronized in the same thread.
 */
typedef struct __pkl_exec_t pkl_exec_t;

/**
 * The callback that gets called when a message is received from Pkl.
 *
 * Messages must be deserialized to Pkl's Message Passing API:
 * https://pkl-lang.org/main/current/bindings-specification/message-passing-api.html
 *
 * @param[in] length    The length of the message bytes
 * @param[in] message   The message itself
 * @param[in] userData  User-defined data passed in from pkl_init.
 */
typedef void (*pkl_message_response_handler)(unsigned int length, char *message,
		void *userData);

/**
 * Initializes and allocates a Pkl executor, writing it to the slot pointed by `exec`.
 *
 * To clean up resources allocated by the executor, use `pkl_close()`.
 *
 * All calls using this executor should come from the same thread.
 *
 * @param[in] handler   The callback that gets called when a message is received from Pkl.
 * @param[in] userData  User-defined data that gets passed to handler.
 * @param[out] exec      The pointer to write the created pkl_exec_t to.
 * @param[out] error     The pointer to write error details to. Can optionally be `NULL`.
 *
 * @return 0 on success, non-zero on failure.
 */
PKL_EXPORT int pkl_init(pkl_message_response_handler handler, void *userData,
		pkl_exec_t **exec, pkl_error_t *error);

/**
 * Send a message to Pkl, providing the length and a pointer to the first byte.
 *
 * Messages must be serialized according to Pkl's Message Passing API:
 * https://pkl-lang.org/main/current/bindings-specification/message-passing-api.html
 *
 * If a message is incorrectly serialized, returns `PKL_ERR_PROTOCOL`.
 * If called from a different thread than `pkl_exec_t`'s originating thread, returns
 * `PKL_ERR_THREAD`.
 *
 * @param[in] pexec     The Pkl executor instance.
 * @param[in] length    The length of the message, in bytes.
 * @param[in] message   The message to send to Pkl.
 * @param[out] error    The pointer to write error details to. Can optionally be `NULL`.
 *
 * @return 0 on success, and non-zero otherwise.
 */
PKL_EXPORT int pkl_send_message(const pkl_exec_t *pexec, unsigned int length,
		char *message, pkl_error_t *error);

/**
 * Cleans up any resources that were created as part of the `pkl_init` process
 * for our `pkl_exec_t` instance.
 *
 * If called from a different thread than `pkl_exec_t`'s originating thread, returns
 * `PKL_ERR_THREAD`.
 *
 * @param[in] pexec     The Pkl executor instance.
 * @param[out] error    The pointer to write error details to. Can optionally be `NULL`.
 *
 * @return 0 on success, -1 if `pexec` is `NULL`, and an error code otherwise.
 */
PKL_EXPORT int pkl_close(pkl_exec_t *pexec, pkl_error_t *error);

/**
 * Returns a null-terminated string indicating Pkl's version.
 */
PKL_EXPORT const char* pkl_version();
----

== Compatibility

libpkl links `native-image`'s runtime internals statically, so the shared library's only external dynamic dependencies are the platform C library, `zlib`, and, on macOS, the `Foundation` and `CoreServices` frameworks.

The C API is ABI compatible across Pkl versions; the underlying Pkl version is available via `pkl_version()`.

== Future directions

https://openjdk.org/jeps/472[JEP 472: Prepare to Restrict the Use of JNI] landed in JDK 24 and may be relevant in the future.

== Alternatives considered

N/A

== Acknowledgements

N/A
